# Auto-generated by tools/gen_overlay_bp.py.
# RRO overlay packages (extract-utils has no overlay/ handler; the
# matching android_app_import modules are in vendor Android.bp).

PRODUCT_PACKAGES += \
    DisplayCutoutEmulationCornerOverlay \
    DisplayCutoutEmulationDoubleOverlay \
    DisplayCutoutEmulationHoleOverlay \
    DisplayCutoutEmulationTallOverlay \
    DisplayCutoutEmulationWaterfallOverlay \
    FontNotoSerifSourceOverlay \
    NavigationBarMode3ButtonOverlay \
    NavigationBarModeGesturalOverlay \
    WifiSystemResMainlineOverlay \
    WifiSystemResOverlay \
    FrameworkResOverlay \
    FrameworkResOverlayExt \
    MtkSettingsResOverlay \
    SettingsProviderResOverlay \
    WifiResGoogleOverlay \
    WifiResMainlineOverlay \
    WifiResOverlay
